### ISSUE TITLE
How to install system wide, ie in /usr/local

### ISSUE THREAD

**Issue by julien-f** [mklement0/n-install#11]
```
curl -L https://git.io/n-install | N_PREFIX=/usr/local bash -s -- lts
```

I get:

```
n-install: ERROR:
  Target directory '/usr/local' already exists and is not empty.
  Make sure it is completely empty, then try again.
```

**Comment by mklement0** [comment]
`n-install` isn't really designed for system-wide installation, but you can do it with a few extra steps.

I'm curious: what is your use case? Multiple *human* users sharing the installation, or software running with a different user identity?

Here's how to install to `/usr/local/opt/n`:

```sh
curl -L https://git.io/n-install | N_PREFIX=/usr/local/opt/n bash -s -- lts
```
* You may need `sudo`; on macOS, if you have Homebrew installed, you do not. If you do need `sudo`, you'll later also need it to run `n` and to  install npm packages globally.

* While your shell initialization file(s) are still updated to define env. variable `N_PREFIX` and to add `/usr/local/opt/n/bin` to the `PATH`, you must  also define `export N_PREFIX=/usr/local/opt/n` in a _global_ shell initialization file such as `/etc/profile/` (`sh`, `bash`, `ksh`) or `/etc/zshenv` (`zsh`); add the following line (requires `sudo`):

      export N_PREFIX=/usr/local/opt/n; PATH+=":$N_PREFIX/bin"

  In the simplest case:

      sudo sh -c "echo 'export N_PREFIX=/usr/local/opt/n; export PATH+=\":\$N_PREFIX/bin\"' >>/etc/profile"

  You _must_ have `N_PREFIX` defined for `n` to work properly, but if you'd rather not modify the `PATH` env. variable, you can create symlinks to the executables in `/usr/local/bin` as follows:

      cd /usr/local/bin
      ln -s ../opt/n/bin/* .

* When you later uninstall `n` with `n-uninstall`, you'll have to manually revert the changes to the global shell initialization files, and, if applicable, remove the manually created `n npm n-uninstall n-update` symlinks.

**Comment by julien-f** [comment]
Waou, thanks for this complete answer! 😍
My use case is a service in a VM, running as a system daemon, so I prefer installing globally 😃

I eventually used `n` directly for my use case, but I will keep your answer in reserve in case I need it!
