### ISSUE TITLE
Can't install global packages (permission denied)

### ISSUE THREAD

**Issue by boorac** [mklement0/n-install#12]
## Description 
I have installed n using n-install. Global installs can't be performed.

```
whereis n
n: /home/matteo/n/bin/n
```
```
echo $PATH
...:/home/matteo/n/bin:...
```

```
echo $N_PREFIX 
/home/matteo/n
```
## Shell
zsh

## Expected Behavior

npm install -g ethereumjs-testrpc should install package to $N_PREFIX

## Actual Behavior

```
npm ERR! Linux 4.8.0-42-generic
npm ERR! argv "/home/matteo/n/bin/node" "/home/matteo/n/bin/npm" "install" "-g" "ethereumjs-testrpc"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! path /usr/local/lib
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib'
npm ERR!     at Error (native)
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/matteo/npm-debug.log

```

**Comment by mklement0** [comment]
It sounds like `npm config get prefix` isn't what it should be. Did you change it manually?

I just ran a clean install on Ubuntu 16.04 and didn't see the problem.

Please run `npm config set prefix "$N_PREFIX"` and try again.

**Comment by boorac** [comment]
Yes, it turns out that I changed it while following the https://docs.npmjs.com/getting-started/fixing-npm-permissions guide.

Changing the prefix resolved the issue. Thanks for the help, I'm closing this :+1:

**Comment by mklement0** [comment]
Glad I could help.
