### ISSUE TITLE
When setting custom  N_PREFIX to any absolute dir, it always prependd a "/root" prefix to the path

### ISSUE THREAD

**Issue by aruizca** [mklement0/n-install#15]
So something like this that is execute as root:
```bash
curl -L https://git.io/n-install | N_PREFIX=/usr/local/opt/n bash -s -- -y lts
```
will output the following N_PREFIX variable
```bash
root@whatever:~# echo $N_PREFIX
/root/usr/local/opt/n
```

**Comment by mklement0** [comment]
I've just tested on macOS and I don't see the problem here. What platform?

Note that, generally, n-install is better installed in the context of a given user account, not as root.

**Comment by aruizca** [comment]
This is on a Ubuntu Linux distribution.

I am using your script to install n in a remote agent of a CI engine called Bamboo. It is working well, just noticed that small issue that I fix by exporting the N_PREFIX variable again to the right path.

**Comment by mklement0** [comment]
Unfortunately, I don't know about Bamboo, but running your command interactively on Ubuntu 16.04 I don't see the symptom (note that, as usual, you must source `~/.bashrc` to make the changes take effect in the same session in which you ran the install).

I'm closing this for now.

If you have a reproducible case involving Bamboo, perhaps you can write it up for the [Wiki](https://github.com/mklement0/n-install/wiki).
