### ISSUE TITLE
Option to install on {path}/.n

### ISSUE THREAD

**Issue by vitordino** [mklement0/n-install#16]
Leaving a visible folder disturbs me, can you develop an option to do thar

(attachment just see where the change is needed on the install script)

[n-install.zip](https://github.com/mklement0/n-install/files/1212884/n-install.zip)

**Comment by mklement0** [comment]
You already have that option, by prepending `N_PREFIX=...` to the `bash` invocation:

```sh
curl -L https://git.io/n-install | N_PREFIX=~/.n bash
```
