### ISSUE TITLE
env: bash\r: No such file or directory

### ISSUE THREAD

**Issue by hyperknot** [mklement0/n-install#17]
Right now, on a clean environment, installing n or n stable results in this exception. The installation is not functional. 

```
-- Cloning https://github.com/tj/n to '/Users/user/n/n/.repo'...
-- Running local n installation to '/Users/user/n/bin'...
-- Shell initialization file '/Users/user/.bash_profile' updated.
-- Installing helper scripts in '/Users/user/n/bin'...
-- Installing the requested Node.js version(s)...
   1 of 1: stable...
env: bash\r: No such file or directory
n-install: WARNING: Failed to install version 'stable'.
=== n successfully installed.
  Run `n stable` to install the latest stable Node.js version.

  Run `n -h` for help.
  To update n later, run `n-update`.
  To uninstall, run `n-uninstall`.

  IMPORTANT: OPEN A NEW TERMINAL TAB/WINDOW or run `. ~/.bash_profile`
             before using n and Node.js.
===
```

After reopen:

```
$ n
env: bash\r: No such file or directory
```

**Comment by hyperknot** [comment]
Running `dos2unix *` in ~/n/bin fixes it. I believe some contributor pushed a PR with Windows line endings.

**Comment by mklement0** [comment]
I don't see any evidence that something is wrong with the line ending in the `n` repo (which is the one that matters here).

Could it be that your local `git` is configured to check out files with Windows line endings? See http://stackoverflow.com/a/29045187/45375

If so, I'm curious why - what platform are you on?

**Comment by mklement0** [comment]
I'll close this for now, but we can reopen, if needed.

**Comment by hyperknot** [comment]
@mklement0 you were so right, I've recently introduced an `autocrlf` config to my `.gitconfig`.
The problem was that I was using the `true` value, whereas the right settings is `input`.

**Comment by mklement0** [comment]
Good to know about this pitfall, thanks for letting me know.

**Comment by mklement0** [comment]
@hyperknot: I've published an update that now guards against the scenario of an unexpected `core.autocrlf` value.
