### ISSUE TITLE
n doesn't work with runuser

### ISSUE THREAD

**Issue by vctfernandes** [mklement0/n-install#19]
Hey guys,

I have a fresh Ubuntu install where I ran the `https://git.io/n-install` script to install node.
Everything works ok, however, I have a bash script to update packages and node, something like this:

```
#!/bin/bash
apt-get update
apt-get -y upgrade
apt-get -y dist-upgrade
apt-get -y autoremove --purge
apt-get -y autoclean
apt-get -y clean
runuser -l vitor -c 'n lts'
runuser -l vitor -c 'npm update -g'
```
And it gives the following error when I run it with sudo:
```
-bash: n: command not found
-bash: npm: command not found
```

Any idea how to fix it?

**Comment by mklement0** [comment]
`n-install` is primarily designed to perform a user-level install.

Therefore, by default, other user accounts won't see such installations.

A [wiki article describes how to perform a system-wide installation](https://github.com/mklement0/n-install/wiki/System%E2%80%90wide-installation), but it requires extra work.

**Comment by vctfernandes** [comment]
What if I told you that "vitor" is the user running the script?

**Comment by vctfernandes** [comment]
Theoretically, he should be able to see node, right?

**Comment by mklement0** [comment]
If it's the same user, why are you using `runuser`?

The problem is likely with the `-l` option of `runuser`, which resets the current shell's environment variables and initializes only a select few (see `man runuser`) - and your `~/.bashrc` file, which defines the env. variables of interest is by default _not_ loaded when you create a _login_ shell (`-l`).

Not sure what your use case is, but using `--preserve-environment` instead of `-l` may do what you want.

**Comment by vctfernandes** [comment]
The idea behind runuser is to not run those commands as root.

I’ve tested `N_PREFIX` with `runuser -l` and it’s loaded, according to `.bashrc`.
What I'm actually doing is to run the script as `vitor` and then run the apt stuff with sudo, so I’m just curious to why this doesn’t work.

**Comment by mklement0** [comment]
Generally: `runuser -l` will _only_ load `~/.bashrc` if you happen to have added an explicit command to `~/.bash_profile` to source the former from there - that's not something you can generally rely upon.

> I’ve tested `N_PREFIX` with `runuser -l` and it’s loaded, according to `.bashrc`.

I don't know what you mean by that.

**Comment by vctfernandes** [comment]
Let me explain myself a little better:
What I meant to say was that I ran: `runuser -l vitor -c '$(N_PREFIX)'` and it returned `/home/vitor/n`, as it's declared in `.bashrc`.

However, I tried that again and now `runuser -l vitor -c '$(N_PREFIX)'` didn't return the path, so at least, it's making sense now 😅
Just for the record: `--preserve-environment` doesn't help.

**Comment by mklement0** [comment]
I assume you mean `runuser -l vitor -c 'echo $N_PREFIX'`, and, yes, that's a good test.

You can try to source `~/.bashrc` directly, with something like the following:

`runuser -l vitor -c '. .bashrc; n lts'`
