### ISSUE TITLE
OpenSuse fails

### ISSUE THREAD

**Issue by texttechne** [mklement0/n-install#2]
Install script fails on openSUSE 10.3 (i586):
```
./n-install.sh: line 153: syntax error in conditional expression: unexpected token `|'
./n-install.sh: line 153: syntax error near `|^'
./n-install.sh: line 153: `  [[ $(shopt -s nullglob dotglob; cd "$1"; echo *) =~ ^$|^\.DS_Store$ ]]'
```
Any ideas?

**Comment by mklement0** [comment]
Possibly an outdated Bash version. What does `bash --version` report?

**Comment by texttechne** [comment]
`GNU bash, version 3.1.23(1)-release (i686-pc-linux-gnu)`

**Comment by texttechne** [comment]
Wow, a relic of an os... it's not even supported anymore.

Thanks! And cheers for the quick reply!

**Comment by mklement0** [comment]
My pleasure; yes, Bash 3.1 is quite old; n-install requires at least Bash 3.*2*, due to use of `=~`, the regex-matching operator. I'll add a runtime version check so that it at least fails gracefully.

**Comment by texttechne** [comment]
Cool. I am in the best position to test that :-)

Strange: /bin/bash refers to `bash version 3.1.23`
However zippy and rpm tell me, that `bash-3.2-61` is installed...
I know its completely unrelated to n-install, but you don't have any ideas by chance?

**Comment by mklement0** [comment]
:) The update is in place; do let me know if the version check works.

You may have an additional, user-installed Bash in the $PATH somewhere.

However, `/bin/bash` seems to come first, because it's the one that runs `n-install`.
`n-install` uses the following shebang line, which means that it runs the first `bash` that is found in the $PATH: `#!/usr/bin/env bash`.

Thus, if you locate the 3.2.61 version and invoke `n-install` with that version FIRST in the $PATH, you should be able to run it; e.g., if the newer Bash version is in `/usr/local`, run `PATH="/usr/local/bin:$PATH" n-install ...`

**Comment by texttechne** [comment]
Ok, after having forced an update to 3.2 i was unable to test. But I've found the sources for 3.1...

Unfortunately, the test results are negative: The new function `isMinBashVersion()` is never evaluated, because it is a syntax error. So the error occurs while parsing the script.

You would need two scripts: The first one which checks the min requirements and fails, and the second script with the main logic and thus with the more "advanced" language features.

**Comment by mklement0** [comment]
Thanks for trying. Can you show me the specific syntax error  you get in 3.1? If you're up for it, can you try the function in isolation? I was hoping that the function itself also runs on 3.1. If we're lucky, placing it earlier in the script would make the test work.

**Comment by texttechne** [comment]
You can find the syntax error in the first comment. And I already tried to place the function call earlier in the script. No success. Hence I reasoned, that it is parsing time not execution time when the error is raised.

**Comment by mklement0** [comment]
Thanks. Try my latest update (0.1.9) - I've verified that it works with Bash 3.1.23.

Bash doesn't do all of its parsing ahead of time, so I was able to place the invocation of `isMinBashVersion()` right after its definition, without breaking the script.

**Comment by texttechne** [comment]
yeap, works. thought I did the same... ok, then bash is not like most programming languages, at least not in this regard.

**Comment by mklement0** [comment]
Yes; generally not a good thing, but occasionally it comes in handy, as in this case.

I've also added the 3.2+ requirement to the read-me.

Thanks for your help.

**Comment by texttechne** [comment]
Thanks for yours.
