### ISSUE TITLE
Adding checksums for downloaded helpers?

### ISSUE THREAD

**Issue by Phyks** [mklement0/n-install#20]
Hi,

First of all, thanks for these install scripts which make `n` installation pretty easy!

I am considering using `n-install` as part of an automated install process, then I was considering the [manual installation](https://github.com/mklement0/n-install#manual-installation) procedure, to avoid the pitfall of `curl|sh`-ing unknown stuff in an automated pipeline.

I quickly had a look through the `n-install` script (it's very well documented btw, thanks!), and noticed [this section](https://github.com/mklement0/n-install/blob/master/bin/n-install#L743-L790) which will download the other helpers (`n-{uninstall,upgrade}`) if they are not available locally. This is not indicated in the `README.md` and might be worth a note in the manual installation section, in my opinion (I can make a PR for this if you want).

Also, helpers scripts are downloaded [without checksums](https://github.com/mklement0/n-install/blob/master/bin/n-install#L777-L779), so the `curl|sh` pitfall that I was trying to avoid by manual installation might come back. As these scripts are not updated often and are all under the same repository, what about adding a checksum (typically, computing `sha256sum` and ensuring the checksum from the downloaded script match the hardcoded one in the `n-install` script)?

Thanks!

**Comment by mklement0** [comment]
@Phyks: Thank you for your nice and thoughtful feedback.

I've updated the read-me, as you've suggested.

As for the checksum:  Good idea, but I have questions:

Is SHA-256 sufficient? (I know little about these things).

Note that the script must work on both macOS and Linux distros. On macOS,  `shasum` is preinstalled. On Linux, there's `sha256sum` - can the latter be assumed to be present on all major Linux distros?

**Comment by Phyks** [comment]
I think `sha256sum` is the currently recommended hash function. 

From testing on my mac it should be `shasum -a 256`. This is available on my Linux laptop as well, but I'm not sure it is really standard.

`sha256sum` is part of GNU coreutils and should then be available everywhere (see for instance on [Debian](https://packages.debian.org/stretch/coreutils)).

**Comment by mklement0** [comment]
I've pushed an update that implements the checksums (v0.4) - give it a try.

**Comment by Phyks** [comment]
Awesome, thanks!
