### ISSUE TITLE
Fish shell initialization support

### ISSUE THREAD

**Issue by dweremeichik** [mklement0/n-install#21]
Leaving this for anyone else who needs this to work in [fish shell](https://fishshell.com/).
```fish
# Add to path
begin
    if not set -q N_PREFIX
        # Change this to what your "n" prefix is supposed to be. 
        set -xU N_PREFIX "$HOME/n"
    end
    if not contains -- "$N_PREFIX/bin" $fish_user_paths
        set -U fish_user_paths "$N_PREFIX/bin" $fish_user_paths
        echo "Updated PATH: $PATH"
    else
        echo "Not updated, already in PATH."
    end
    
end

########################

# Remove from path
begin
    if set -l index (contains -i "$N_PREFIX/bin" $fish_user_paths)
        set --erase --universal fish_user_paths[$index]
        echo "Updated PATH: $PATH"
    else
        echo "Not updated, not in PATH."
    end
    # Remove N_PREFIX
    set --erase --universal --unexport N_PREFIX
    
end
```
The installer could probably be made to call these through fish to set it up (piping). Note that these only need to be called once, either to install/add or to remove, unlike bash needing it called by every shell. Also, these could probably be crunched into one liners if desired.

**Comment by mklement0** [comment]
Thanks, @johncmunson.

`fish` initialization-file support, along with support for `pwsh` (PowerShell), is now implemented (v0.6.1).
