### ISSUE TITLE
Add support for n architecture argument

### ISSUE THREAD

**Issue by alexmcroberts** [mklement0/n-install#22]
There are certain platforms that require specific architecture support. For example, the NVIDIA Jetson TX2, which requires the arm64 architecture.

To do this with `n` the command is:

```
n -a arm64 9.2.1
```

**Comment by mklement0** [comment]
@alexmcroberts: Please try with the latest version (v0.4.1) - https://github.com/mklement0/n-install/commit/797d834af28f46b9eb962fc6d618ca10169fe032
