### ISSUE TITLE
Stable is no longer used to identify node versions

### ISSUE THREAD

**Issue by JohnRGee** [mklement0/n-install#23]
Short version: I suggest removing use of `stable` and moving to use `lts` instead.

Long version

The node project started out using even minor numbers for stable versions and odd version numbers for internal development versions. This is still what `n` assumes for `stable` but is no longer meaningful:
- https://nodesource.com/blog/nodejs-is-semver/
- https://github.com/tj/n/issues/335
- https://github.com/tj/n/issues/354

The home page for [NodeJS](https://nodejs.org/en/) currently lists the downloads as:
- 8.11.3 LTS, Recommended For Most Users
- 10.7.0 Current, Latest Features

I suggest that LTS would be the appropriate version as the default node install for `n-install`.

Willing to work on a PR if that would be helpful.

Disclaimer: I am an enthusiastic `n` user rather than `n-install`. I have a vested interest in raising this issue as I expect `n` is reluctant to change behaviour while closely related projects are still using `stable`. Feel free to close this and wait for a direct user to raise this issue!

**Comment by mklement0** [comment]
@JohnRGee: Thanks for bringing this to my attention.

I've just published v0.5.0, which now uses `lts` as the default.
I've remove references to `stable` in the read-me and the CLI help, and I've added a brief rational to the changelog.

**Comment by JohnRGee** [comment]
Thanks! Nice description in the changelog too.

**Comment by mklement0** [comment]
Thanks, @JohnRGee.

I've also submitted an issue to the `n` repo with suggested terminology changes: https://github.com/tj/n/issues/522
