### ISSUE TITLE
git.io/n-install unavailable

### ISSUE THREAD

**Issue by janjitsu** [mklement0/n-install#25]
I'm getting 503 when trying to install n. Is there an alternative for installing it silently?

**Comment by mklement0** [comment]
A 503 error ("service unavailable") is usually an _intermittent_ error that should eventually go away.
Or is it happening consistently for you?

I'm unclear on what you mean by installing _silently_.
`-q` will suppress _status_ information, but it will still surface _errors_ - as it should.

What behavior, specifically, are you looking for?

**Comment by janjitsu** [comment]
Sorry, I meant automatic (no selecting options) and indeed, I know is temporary, I've switched to downloading from the repo, thanks!

**Comment by mklement0** [comment]
Note that you can defer installing any Node.js versions as follows (installs just `n` itself):

```sh
# Install quietly, without any Node.js versions - use `n` to install them later.
curl -L https://git.io/n-install | bash -s -- -q -
```

**Comment by janjitsu** [comment]
That's exactly how I'm doing! Thanks and sorry for bothering!


Jan Silva


Em seg, 3 de set de 2018 às 18:43, Michael Klement <notifications@github.com>
escreveu:

**Comment by mklement0** [comment]
No worries - I'm glad you find n-install useful.
