### ISSUE TITLE
Which directories are the binaries written to?

### ISSUE THREAD

**Issue by der-Daniel** [mklement0/n-install#26]
Hi,

can I get all the directories and file `n-install` writes on my system?
I have managed to screw some things up and need to manually delete all the file `n-install` put on my system.

I am using Arch.

Cheers
Daniel

**Comment by mklement0** [comment]
Hi, @der-Daniel:

The `N_PREFIX` environment variable in your shell should tell you n-install's installation directory; by default, it is `~/n`.
