### ISSUE TITLE
Use ZDOTDIR to determine location of .zshrc

### ISSUE THREAD

**Issue by danteissaias** [mklement0/n-install#28]
The location of `.zshrc` is not always in the home directory. It can be set to any folder with the environment variable `ZDOTDIR`. When configuring `n` for `zsh` the `ZDOTDIR` should be used to determine the location of `.zshrc`.

**Comment by mklement0** [comment]
Thanks, @danteissaias  - this should be fixed now.

**Comment by iamareebjamal** [comment]
```
 curl -L https://git.io/n-install | zsh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0FATAL ERROR: This script requires Bash 3.2 or higher. You're running:
 31 39444   31 12339    0     0   3702      0  0:00:10  0:00:03  0:00:07 33991
curl: (23) Failed writing body (1320 != 1371)
```

**Comment by mklement0** [comment]
@iamareebjamal

Please not that you mustn't pipe to `zsh` - you must pipe to `bash`.

What shell's initialization shell is updated is solely determined by what your _default_ shell is, as reflected in `$SHELL`. That is, if `$SHELL` points to `zsh`, `.zshrc` will be updated.

If you still seen an error when you run `curl -L https://git.io/n-install | bash` instead, please open a new issue.

**Comment by iamareebjamal** [comment]
Thanks, that worked
