### ISSUE TITLE
Don't update shell rc files unless told to

### ISSUE THREAD

**Issue by jsumners** [mklement0/n-install#3]
Some of us don't compose our shell rc files in the way n-install assumes everyone does, e.g. https://github.com/jsumners/dotfiles/blob/master/zshrc#L65 . It'd be great if n-install didn't make such an assumption, or could at least be told to not do so.

**Comment by mklement0** [comment]
If I understand correctly, you're "outsourcing" your exported variables to a separate file that you source from the standard init file, and that you want to keep _all_ exports there, correct?

What behavior are you looking for?

* tell `n-install` to _suppress_ updating the standard init file?
* pass an explicit file path to `n-install` for it to update in lieu of the standard init file?

Or both?

**Comment by jsumners** [comment]
I'd prefer option 1.  But if you're up for option 2, I'm sure some people would find it very useful.

**Comment by mklement0** [comment]
I've published version 0.2.0, which adds option `-n` to suppress modification of shell-initialization files. 

I'm holding off on the ability to specify an alternate init file to modify until people start asking for it.

Hope that helps.

**Comment by jsumners** [comment]
Awesome. Thank you.
