### ISSUE TITLE
Install to custom path

### ISSUE THREAD

**Issue by vladimircores** [mklement0/n-install#32]
Please add prompt option to choose path to install `n`.

Related to https://github.com/tj/n/issues/631

**Comment by mklement0** [comment]
Note that you can set environment variable `N_PREFIX` to the desired installation dir. before installing; e.g.:

```
curl -L https://git.io/n-install | N_PREFIX=/path/to/folder
```

Or are you looking for an interactive prompt, specifically?

**Comment by vladimircores** [comment]
It was the feature request. But your @mklement0 answer satisfies my needs, thank you : )

**Comment by mklement0** [comment]
Glad to hear it, @vladimircores.
