### ISSUE TITLE
Should prefer .bash_profile if exists

### ISSUE THREAD

**Issue by frank-dspeed** [mklement0/n-install#35]
On many linux distros .bash_profiles is also the default main entry for bash and only loads .bashrc if it exists.

so i would propose to check for the existence of .bash_profile and if it exists use that as it makes backups more easy
as .bash_profile can be even the only file that exists on linux and it does not always load .bashrc

**Comment by mklement0** [comment]
I only know a few Linux distros, but in my experience their terminal applications run interactive `bash` sessions as _non-login_ shells, which means that `~/.bash_profile` is _not_ processed.

On what distros is this different, and can they be reliably identified, without hard-coding distro names?

In general, I'd like to avoid special-casing.

**Comment by mklement0** [comment]
I'll close this for now; we can revisit if you have more information.
