### ISSUE TITLE
npm not found

### ISSUE THREAD

**Issue by humbienri** [mklement0/n-install#36]
Hello!

I just finished installing n on Debian WSL 2. Had a couple of hiccups since git does not come with the Debian WSL-flavored version of Debian.

Now I can't seem to run npm. It's as if it doesn't exist. I get:

`/usr/bin/env: ‘node’: Input/output error`

Any thoughts what I might have done wrong?

Thanks!

**Comment by mklement0** [comment]
Unfortunately, I can't tell what the problem is, but it sounds like a pretty fundamental one. Perhaps something along the lines of https://github.com/microsoft/WSL/issues/6174?
