### ISSUE TITLE
Provide resolved bit.ly link in the readme

### ISSUE THREAD

**Issue by cachius** [mklement0/n-install#48]
I understand that the bit.ly link is short and convenient, but please mention the resolved url at least once in the Readme. Especially since you introduce it under "Installing from GitHub". This would be
`https://raw.githubusercontent.com/mklement0/n-install/stable/bin/n-install`
Inserting not formatted as code results in https://raw.githubusercontent.com/mklement0/n-install/stable/bin/n-install

**Comment by mklement0** [comment]
I've added a note in the introduction section, just below the first command.

**Comment by cachius** [comment]
@mklement0 Just stumbled over [this Chocolatey install hint](https://chocolatey.org/install#individual-method):

> NOTE
Please inspect https://community.chocolatey.org/install.ps1 prior to running any of these scripts to ensure safety. We already know it's safe, but you should verify the security and contents of any script from the internet you are not familiar with. All of these scripts download a remote PowerShell script and execute it on your machine. We take security very seriously. [Learn more about our security protocols](https://docs.chocolatey.org/en-us/information/security).

which reminded me of this issue.
