### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by jsumners** [mklement0/n-install#8]
I have an environment that does not have access to the Internet, but does have access to an intermediary server. So I for these local only systems I plan to mirror nodejs.org/dist/ (or most of it) to this intermediary and deploy Node from there. I would like to be able to use n-install to do the deploying. From what I can tell, two things would need to be supported for that to happen:

1. I would need to be able to deploy all of n-install offline. Something like the manual script that unbundles the rest of the scripts and the does the rest of the work.
2. The installed n-install would need to support specifying the download server and base URI.

In regard to number 1, it's rather easy to create a self-extracting bash script:

```bash
#!/bin/bash
# simple bash self extracting script builder

tar cf - stage/ | bzip2 -9 > stage.tar.bz2

cp install-src.sh installer.sh
echo -e "\n\n" >> installer.sh

echo "PAYLOAD=\"$(base64 stage.tar.bz2)\"" >> installer.sh
echo '' >> installer.sh
echo 'unpack ${PAYLOAD}' >> installer.sh
echo 'doInstall' >> installer.sh # a function in install-src.sh
```

My use case may be unique, so I understand if you don't want to implement it.

**Comment by mklement0** [comment]
`n-install` simply passes the requested or implied version numbers to `n` when it comes to installing Node.js versions - `n-install` has no control over where these versions are downloaded from.

Therefore, you'd first need to convince the maintainers of `n` to allow installation from an alternative source. 

If you succeed in that, I'm happy to modify `n-install` accordingly.

**Comment by jsumners** [comment]
Looks like they do support it -- https://github.com/tj/n/blob/master/bin/n#L35 . So that solves number 2 of my request; I'd just have to export `NODE_MIRROR` prior to running n-install.

**Comment by mklement0** [comment]
Yes, but it looks like the required environment variables to set are actually `PROJECT_NAME` and `PROJECT_URL`, if you want to define a custom installation URL - this needs to be accompanied by invoking `n` as `n project`, according to the [read-me](https://github.com/tj/n#custom-source).

I'll look into it.

**Comment by jsumners** [comment]
That's if you're trying to install some alternative JS environment like Echo JS (https://github.com/toshok/echojs). As long as a local mirror is a true mirror of nodejs.org/dist then setting `NODE_MIRROR` appropriately should be all that is necessary.

**Comment by mklement0** [comment]
I see, thanks for clarifying. So you're all set then?

**Comment by jsumners** [comment]
Well, it looked to me like `n-install` depends upon access to github.com/io. If that is true, then I'd still need it to support an, essentially, offline mode.

**Comment by mklement0** [comment]
I assume you're referring to [io.js](https://iojs.org/en/), which is obsolete now, because it merged with Node.js again, so Node.js is really the only game in town:

> io.js has merged with the Node.js project again.
There won't be any further io.js releases. All of the features in io.js are available in Node.js v4 and above.

I suppose I could remove io.js from `n-install` eventually, but it sounds like you needn't worry about that, correct?

**Comment by jsumners** [comment]
No, the alternate TLD you reference for github in your scripts.

**Comment by mklement0** [comment]
Sorry that I forgot to respond. the TLD http://git.io is used for GitHub's URL shortener service.

http://git.io/n-install simply redirects to https://raw.githubusercontent.com/mklement0/n-install/stable/bin/n-install

Given that you're planning to run an offline copy of `n-install`, however, that doesn't come into play, right?

**Comment by jsumners** [comment]
I closed the issue because I realized I was making things more complicated than they need to be. I really dig `n-install` for easily installing `n`, and was stupidly hell bent of using it to install `n` on these isolated systems. I realized this morning that I simply need to copy `n` to them, and `n-install` doesn't need to be involved.

**Comment by mklement0** [comment]
Cool, thanks for letting me know.
